# diskmind configuration

hosts:
  - ssh:root@192.168.37.10
  - push:192.168.28.15
  - push:192.168.28.10
  # - root@192.168.1.2

ssh:
  timeout: 30

database:
  path: ./data/smart.db
  retention_days: 365

# Threshold preset: backblaze, conservative, relaxed
threshold_preset: backblaze
delta_preset: 7d
push_token: mysecret
