# diskmind configuration

hosts:
  - ssh:192.168.37.10
  - push:192.168.28.15
  - push:192.168.28.10
  # - 192.168.1.2

ssh:
  user: root
  timeout: 30

database:
  path: ./data/smart.db
  retention_days: 365

# Threshold preset: backblaze, conservative, relaxed
threshold_preset: backblaze
delta_preset: 24h
push_token: hodldiplom
